// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import CounterController from "./counter_controller"
import { Alert, Tabs } from "tailwindcss-stimulus-components"
application.register("counter", CounterController)
application.register("alert", Alert)
application.register("tabs", Tabs)
